config/routes.rb
Rails.application.routes.draw do

  root 'users#new'
  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  delete '/room/destroy/:id', to: 'users#destroy_room', as: 'room_destroy'
  post '/room/new', to: 'users#create_room', as: 'room_create'

  resources :users
  resources :students do
    collection do
      get :search
    end

    get :get_teachers, on: :member
  end
  resources :teachers do
    collection do
      get :search
    end

    get :get_students, on: :member
  end
  resources :class_rooms do
    collection do
      get :search
    end

    get :get_teachers, on: :member
  end
end

app/models/student.rb
class Student < User

  validates :name, presence: { message: "用户名不能为空" }
  validates :name, uniqueness: { message: "用户名已存在" }

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.where(mold: 'Student').page(params[:page] || 1).per_page(params[:per_page] || 10).order("id desc")
  end

  def new
    @student = Student.new
  end

  def create
    @student = student.new(student_attrs)
    if @student.save
      flash[:notice] = "学生创建成功"
      redirect_to students_path
    else
      flash[:notice] = "学生创建失败"
      render action: :new
    end
  end

  def show
    @student = Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.attributes = student_attr
    if @student.save
      flash[:notice] = "学生信息更新成功"
      redirect_to students_path
    else
      flash[:notice] = "学生信息更新失败"
      redirect_to :back
    end
  end

  def search
    @students = Student.page(params[:page] || 1).per_page(params[:per_page] || 10)
    .order("id desc").where(["name like ?", "%#{params[:name]}%"])

    render action: :index
  end

  def get_students
    student = Student.find params[:id]
    @teachers = student.class_rooms.first.users.where("mold = 'Teacher' ").all
  end

  private
  def student_attr
    params.require(:student).permit(:name)
  end

  def student_attrs
    params.require(:student).permit(:name, :password, :password_confirmation, :mold)
  end
end

app/views/students/_students.html.erb
<div>
  <% if logged_in? %>
  <% if current_user.admin? %>
  <%= link_to "创建学生", new_student_path, class: "btn btn-primary" %>
  <%= link_to "当前学生", students_path, class: "btn btn-default" %>
  <%= link_to "返回上一级",students_path, class: "btn btn-default" %>
  <% end-%>
  <% end -%>
</div>

app/views/students/edit.html.erb
<h1>学生信息编辑</h1>

<div class="row">
  <div class="col-sm-12">
    <%= form_for(@student, url: student_path(@student), method: :put) do |f| %>
    <div class="form-group">
      <ul class="list-unstyled">
        <% @student.errors.messages.values.flatten.each do |error| %>
        <li><i class="fa fa-exclamation-student"></i><%= error %></li>
        <% end -%>
      </ul>
    </div>

    <div class="form-group">
      <%= f.text_field :name, class:"form-control", placeholder: "用户名" %>
    </div>
    <%= f.submit "保存", class: "btn btn-primary" %>
    <% end -%>
  </div>
  <div class="col-sm-12">
  </div>
</div>

app/views/students/get_teachers.html.erb
<%= render "layouts/header" %>

<div class="row">
  <div class="form-group">
    <table class="table">
      <tr>
        <th>老师姓名</th>
      </tr>
      <% @teachers.each do |teacher| %>
      <tr>
        <th><%= teacher.name %></th>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/students/index.html.erb
<%= render "layouts/header" %>

<div class="row">
  <div class="col-sm-12">
    <table class="table">
      <h1>学生管理</h1>
      <div class="form-group">
        <%= render 'students' %>
      </div>
      <form action="<%= search_students_path %>" method = "get">
        用户名:<input type="text" name="name" value="<%= params[:name] %>" />
        <input type="submit" name="搜索">
      </form>
      <tr>
        <th>ID</th>
        <th>学生姓名</th>
        <th>所在班级</th>
        <th>班级老师</th>
        <th>修改学生所在班级</th>
        <th>编辑学生信息</th>
        <th>删除该学生</th>
        <th></th>
      </tr>
      <% @students.each do |student| %>
      <tr>
        <th><%= student.id %></th>
        <th><%= student.name %></th>
        <%if !student.class_rooms.empty?%>
        <th><%= student.class_rooms.first.roomname %></th>
        <% else %>
        <th>学生不在班级序列</th>
        <% end %>
        <% if !student.class_rooms.first.users.where("mold = 'Teacher'").empty? %>
        <% student.class_rooms.first.users.where("mold = 'Teacher' ").each do |f| %>
        <th><%= f.name %></th>
        <% end %>
        <% else %>
        <th>此班级还未分配老师</th>
        <% end %>
        <th><%= link_to '修改学生所在班级', edit_user_path(student) %></th>
        <th><%= link_to '修改学生信息',  edit_student_path(student)%></th>
        <th><%= link_to '删除该学生', user_path(student), method: :delete,  data: {confirm: "Are you sure?"} %></th>
        <th><%= link_to '班级老师', get_teachers_student_path(student) %></th>
      </tr>
      <% end %>
    </table>

    <%= will_paginate @students %>
  </div>
</div>

app/views/students/new.html.erb
<%= render "layouts/header" %>

<h1>创建学生</h1>

<div class="row">
  <div class="col-sm-5">
    <%= form_for @student, url: students_path, method: :post do |f|  %>
    <div class="form-group">
      <ul class="list-unstyled">
        <% @student.errors.messages.values.flatten.each do |error| %>
        <li><i class="fa fa-exclamation-teacher"></i><%= error %></li>
        <% end -%>
      </ul>
    </div>

    <div class="form-group">
      <%= f.text_field :name, class: "form-control", placeholder: "学生姓名" %>
    </div>

    <div class="form-group">
      <%= f.password_field :password, class: "form-control", placeholder: "密码" %>
    </div>

    <div class="form-group">
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "确认密码" %>
    </div>

    <div>
      <%= f.radio_button(:mold, "Student", checked: true) %>
      <%= f.label(:mold, "sign up as a student") %>
    </div>

    <div>
      <%= f.check_box(:admin, {}, "true", "false") %>
      <%= f.label(:admin, "sign as admin") %>
    </div>

    <%= f.submit "保存", class: "btn btn-primary" %>
    <% end -%>
  </div>
  <div class="col-sm-7">
  </div>
</div>

app/views/students/show.html.erb
<%= render "layouts/header" %>
<h1>学生信息列表</h1>

<div class="row">
  <dl>
    <dt>ID</dt>
    <dd><%= @student.id %></dd>
  </dl>

  <dl>
    <dt>用户名</dt>
    <dd><%= @student.name %></dd>
  </dl>

  <% if !@student.class_rooms.empty? %>
  <dl>
    <dt>所在班级</dt>
    <dd><%= @student.class_rooms.first.roomname %></dd>
  </dl>

  <dl>
    <dt>授课老师</dt>
    <% @student.class_rooms.first.users.where("mold = 'Teacher' ").each do |f| %>
    <dd><%= f.name %></dd>
    <% end %>
  </dl>
  <% end %>
</div>