config/routes.rb
Rails.application.routes.draw do

  root 'users#new'
  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  delete '/room/destroy/:id', to: 'users#destroy_room', as: 'room_destroy'
  post '/room/new', to: 'users#create_room', as: 'room_create'

  resources :users
  resources :students do
    collection do
      get :search
    end

    get :get_teachers, on: :member
  end
  resources :teachers do
    collection do
      get :search
    end

    get :get_students, on: :member
  end
  resources :class_rooms do
    collection do
      get :search
    end

    get :get_teachers, on: :member
  end
end

app/models/class_room.rb
class ClassRoom < ActiveRecord::Base

  has_many :user_and_class_rooms, class_name: "UserAndClassRoom"
  has_many :users, through: :user_and_class_rooms

  validates :roomname, presence: { message: "班级不能为空" }

end

app/controllers/class_rooms_controller.rb
class ClassRoomsController < ApplicationController

  def index
    @class_rooms = ClassRoom.page(params[:id] || 1).per_page(params[:per_page] || 10).order("id desc")
  end


  def search
    @class_rooms = ClassRoom.page(params[:page] || 1).per_page(params[:per_page] || 10)
      .order("id desc").where(["roomname like ?", "%#{params[:roomname]}%"])

    render action: :index
  end

  def get_teachers
    class_room = ClassRoom.find params[:id]
    @teachers = class_room.users.where("mold = 'Teacher' ").all
  end

end

app/views/class_rooms/get_teachers.html.erb
<%= render "layouts/header" %>

<div class="row">
  <div class="form-group">
    <table class="table">
      <tr>
        <th>老师姓名</th>
      </tr>
      <% @teachers.each do |teacher| %>
      <tr>
        <th><%= teacher.name %></th>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/class_rooms/index.html.erb
<%= render "layouts/header" %>

<div class="row">
  <div class="col-sm-12">
    <table class="table">
      <h1>班级管理</h1>
      <form action="<%= search_class_rooms_path %>" method = "get">
        班级名:<input type="text" name="roomname" value="<%= params[:roomname] %>" />
        <input type="submit" name="搜索">
      </form>
      <tr>
        <th>ID</th>
        <th>班级名称</th>
        <th>学生所在班级数量</th>
        <th>老师所在班级数量</th>
        <th>删除班级</th>
        <th>班级老师</th>
        <th></th>
      </tr>
      <% @class_rooms.each do |room| %>
      <tr>
        <th><%= room.id %></th>
        <th><%= room.roomname %></th>
        <% if room.users.exists?(mold: 'Student') %>
        <th><%= room.users.where("mold = 'Student'").size %></th>
        <% else %>
        <th>该班级为空</th>
        <% end %>
        <% if room.users.exists?(mold: 'Teacher')%>
        <th><%= room.users.where("mold = 'Teacher'").size %></th>
        <% else %>
        <th>该班级为空</th>
        <% end %>
        <th><%= link_to '删除班级', "/room/destroy/#{room}", method: :delete, data: {confirm: "Are you sure?"} %></th>
        <th><%=link_to '查找班级老师', get_teachers_class_room_path(room)%></th>
      </tr>
      <% end %>
    </table>

    <%= form_tag(room_create_path, method: :post, class: "form-inline") do %>
    <div class="form-group">
      <%= label_tag(:roomname, "班级名称") %>
      <%= text_field_tag(:roomname) %>
    </div>
    <%= submit_tag "按名字创建班级", class: "btn btn-default" %>
    <% end %>

    <%= will_paginate @class_rooms %>
  </div>
</div>