config/routes.rb
Rails.application.routes.draw do

  root 'users#new'
  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  delete '/room/destroy/:id', to: 'users#destroy_room', as: 'room_destroy'
  post '/room/new', to: 'users#create_room', as: 'room_create'

  resources :users
  resources :students do
    collection do
      get :search
    end

    get :get_teachers, on: :member
  end
  resources :teachers do
    collection do
      get :search
    end

    get :get_students, on: :member
  end
  resources :class_rooms do
    collection do
      get :search
    end

    get :get_teachers, on: :member
  end
end

app/models/teacher.rb
class Teacher < User

  validates :name, presence: { message: "用户名不能为空" }
  validates :name, uniqueness: { message: "用户名已存在" }

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  def index
    @teachers = Teacher.where(mold: 'Teacher').page(params[:page] || 1).per_page(params[:per_page] || 10).order("id desc")
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_attrs)
    if @teacher.save
      flash[:notice] = "老师创建成功"
      redirect_to teachers_path
    else
      flash[:notice] = "老师创建失败"
      render action: :new 
    end
  end

  def show
    @teacher = Teacher.find(params[:id])
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    @teacher = Teacher.find(params[:id])
    @teacher.attributes = teacher_attr
    if @teacher.save
      flash[:notice] = "老师信息更新成功"
      redirect_to user_path(current_user)
    else
      flash[:notice] = "老师信息更新失败"
      redirect_to :back
    end
  end

  def search
    @teachers = Teacher.page(params[:page] || 1).per_page(params[:per_page] || 10)
    .order("id desc").where(["name like ?", "%#{params[:name]}%"])

    render action: :index
  end

  def get_students
    teacher = Teacher.find params[:id]
    @students = teacher.class_rooms.first.users.where("mold = 'Student' ").all
  end

  private
  def teacher_attrs
    params.require(:teacher).permit(:name, :password, :password_confirmation, :mold)
  end

  def teacher_attr
    params.require(:teacher).permit(:name)
  end
end

app/views/teachers/_teachers.html.erb
<div>
  <% if logged_in? %>
  <% if current_user.admin? %>
  <%= link_to "创建老师", new_teacher_path, class: "btn btn-primary" %>
  <%= link_to "当前教师", teachers_path, class: "btn btn-default" %>
  <%= link_to "返回上一级", teachers_path, class: "btn btn-default" %>
  <% end-%>
  <% end -%>
</div>

app/views/teachers/edit.html.erb
<h1>教师信息编辑</h1>

<div class="row">
  <div class="col-sm-12">
    <%= form_for(@teacher,url: user_path(@teacher), method: :put) do |f|%>
    <div class="form-group">
      <ul class="list-unstyled">
        <% @teacher.errors.messages.values.flatten.each do |error| %>
        <li><i class="fa fa-exclamation-circle"></i> <%= error %></li>
        <% end -%>
      </ul>
    </div>

    <div class="form-group">
      <%= f.text_field :name, class: "form-control", placeholder: "用户名"%>
    </div>
    <%= f.submit "保存", class: "btn btn-primary" %>
    <% end -%>
  </div>

  <div class="col-sm-7">
  </div>
</div>

app/views/teachers/get_students.html.erb
<%= render "layouts/header" %>

<div class="row">
  <div class="form-group">
    <table class="table">
      <tr>
        <th>学生姓名</th>
      </tr>
      <% @students.each do |student| %>
      <tr>
        <th><%= student.name %></th>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/teachers/index.html.erb
<%= render "layouts/header" %>

<div class="row">
  <div class="col-sm-12">
    <table class="table">
      <h1>老师管理</h1>
      <div class="form-group">
        <%= render 'teachers' %>
      </div>
      <form action="<%= search_teachers_path %>" method = "get">
        用户名:<input type="text" name="name" value="<%= params[:name] %>" />
        <input type="submit" name="搜索">
      </form>
      <tr>
        <th>ID</th>
        <th>老师姓名</th>
        <th>老师所在班级</th>
        <th>修改老师所在班级</th>
        <th>编辑老师信息</th>
        <th>删除该老师</th>
        <th>班级学生</th>
        <th></th>
      </tr>
      <% @teachers.each do |teacher| %>
      <tr>
        <th><%= teacher.id %></th>
        <th><%= teacher.name %></th>
        <%if !teacher.class_rooms.empty? %>
        <th><%= teacher.class_rooms.first.roomname %></th>
        <% else %>
        <th>老师不在该班级序列</th>
        <% end %>
        <th><%= link_to '修改老师所在班级', edit_user_path(teacher) %></th>
        <th><%= link_to '修改老师信息', edit_teacher_path(teacher) %></th>
        <th><%= link_to '删除该老师', user_path(teacher), method: :delete,  data: {confirm: "Are you sure?"} %></th>
        <th><%= link_to '班级学生', get_students_teacher_path(teacher) %></th>
        <th></th>
      </tr>
      <% end %>
    </table>

    <%= will_paginate @teachers %>
  </div>
</div>

app/views/teachers/new.html.erb
<%= render "layouts/header" %>

<h1>创建老师</h1>

<div class="row">
  <div class="col-sm-5">
    <%= form_for @teacher, url: teachers_path, method: :post do |f|  %>
    <div class="form-group">
      <ul class="list-unstyled">
        <% @teacher.errors.messages.values.flatten.each do |error| %>
        <li><i class="fa fa-exclamation-teacher"></i><%= error %></li>
        <% end -%>
      </ul>
    </div>

    <div class="form-group">
      <%= f.text_field :name, class: "form-control", placeholder: "老师姓名" %>
    </div>

    <div class="form-group">
      <%= f.password_field :password, class: "form-control", placeholder: "密码" %>
    </div>

    <div class="form-group">
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "确认密码" %>
    </div>

    <div>
      <%= f.radio_button(:mold, "Teacher") %>
      <%= f.label(:mold, "sign up as a teacher") %>
    </div>

    <div>
      <%= f.check_box(:admin, {}, "true", "false") %>
      <%= f.label(:admin, "sign as admin") %>
    </div>

    <%= f.submit "保存", class: "btn btn-primary" %>
    <% end -%>
  </div>
  <div class="col-sm-7">
  </div>
</div>

app/views/teachers/show.html.erb
<%= render "layouts/header" %>
<h1>老师信息列表</h1>

<div class="row">
  <dl>
    <dt>ID</dt>
    <dd><%= @teacher.id %></dd>
  </dl>

  <dl>
    <dt>用户名</dt>
    <dd><%= @teacher.name %></dd>
  </dl>

  <% if !@teacher.class_rooms.empty? %>
  <dl>
    <dt>所在班级</dt>
    <dd><%= @teacher.class_rooms.first.roomname %></dd>
  </dl>

  <dl>
    <dt>班级学生</dt>
    <% @teacher.class_rooms.first.users.where("mold = 'Student' ").each do |f| %>
    <dd><%= f.name %></dd>
    <% end %>
  </dl>
  <% end %>
</div>