config/routes.rb
Rails.application.routes.draw do

  root 'users#new'
  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  delete '/room/destroy/:id', to: 'users#destroy_room', as: 'room_destroy'
  post '/room/new', to: 'users#create_room', as: 'room_create'

  resources :users
  resources :students do
    collection do
      get :search
    end

    get :get_teachers, on: :member
  end
  resources :teachers do
    collection do
      get :search
    end

    get :get_students, on: :member
  end
  resources :class_rooms do
    collection do
      get :search
    end

    get :get_teachers, on: :member
  end
end

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<body>
  <header name="top">
    <nav class="navbar navbar-default navbar-fixed-top nav-color" role="navigation" id="nav">
      <div class="container">
        <div class="navbar-header nav-color">
          <button id="nav_collapse" type="button" class="navbar-toggle toggle-btn" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-controls="bs-navbar-collapse-1">
            <span class="fa fa-bars fa-lg"></span>
          </button>
          <a class="navbar-brand custom-logo-link" href="/">
            用户信息管理
          </a>
        </div>

        <div class="collapse navbar-collapse nav-submenu-color collapse" id="bs-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right custom">
            <li>
              <a href="#">Home</a>
            </li>
            <li>
              <li><%= link_to '用户', current_user %></li>
            </li>

            <% if logged_in? %>
            <li><%= link_to "#{current_user.name}, 退出", logout_path, method: 'delete' %></li>
            <% if current_user.admin? %>
            <li><%= link_to '老师管理', teachers_path %></li>
            <li><%= link_to '学生管理', students_path %></li>
            <li><%= link_to '教室管理', class_rooms_path %></li>
            <% else %>
            <li><%= link_to 'log in', login_path %> </li>
            <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <div class="container body-offset">
    <% if flash[:notice] %>
    <div class="alert alert-info"><%= flash[:notice] %></div>
    <% end -%>

    <%= yield %>
  </div>

  <%= javascript_include_tag 'application' %>
  <%= yield :javascripts %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
<head>
  <title>学生信息管理系统</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>